name: Run Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libarmadillo-dev libensmallen-dev
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools pytest numpy scipy pandas
          # Install JAX CPU version which is required for GMM tests
          pip install "jax[cpu]"
      
      - name: Install package in development mode
        run: |
          pip install -e .
      
      - name: Run tests
        run: |
          python -m pytest tests/ -v
      
      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-python-${{ matrix.python-version }}
          path: |
            *.log
            .pytest_cache/